kodkollektivet/kodkollektivet_projects/urls.py
from django.conf.urls import url

from kodkollektivet_projects import github
from kodkollektivet_projects import views

urlpatterns = [
    url(r'^$', views.ProjectsListView.as_view(), name='projectslistview'),
    url(r'^contributor/(?P<slug>\S+)/$', views.ContributorDetailView.as_view(), name="contributordetailview"),
    url(r'^(?P<slug>\S+)/$', views.ProjectsDetailView.as_view(), name="projectdetailview"),
    url(r'^github/webhook$', github.GithubHook.as_view(), name='githubwebhook'),
]

kodkollektivet/urls.py
from django.conf.urls import url

from kodkollektivet import github
from kodkollektivet import views

urlpatterns = [
    url(r'^projects/$', views.ProjectsListView.as_view(), name='projectslistview'),
    url(r'^board/$', views.BoardTemplateView.as_view(), name='boardtemplateview'),
    url(r'^thanks/$', views.ThanksTemplateView.as_view(), name='thankstemplateview'),
    url(r'^events/$', views.EventsListView.as_view(), name="eventslistview"),
    url(r'^event/(?P<slug>\S+)/$', views.EventsDetailView.as_view(), name="eventdetailview"),
]

settings/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

from kodkollektivet import views

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.IndexView.as_view(), name='home'),
    re_path(r'^', include(('kodkollektivet.urls', 'kodkollektivet'), namespace='kodkollektivet')),
    # re_path(r'^i18n/', include('django.conf.urls.i18n')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kodkollektivet/models.py
# -*- coding: utf-8 -*-

from datetime import datetime, timedelta
import os

from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.conf import settings

from wand.image import Image
from wand.drawing import Drawing
from wand.color import Color

def handle_uploaded_file(fname, f):
    with open(fname, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)


class BoardMember(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, blank=True)
    telephone = models.CharField(max_length=50, blank=True)
    photo = models.ImageField(upload_to='board-images/')

    def save(self, *args, **kwargs):
        super(BoardMember, self).save(*args, **kwargs)
        if self.photo:
            with Image(filename=self.photo.path) as img:
                img.save(filename=self.photo.path+'.ORGINAL')
                img.transform(resize='x250')
                img.compression_quality = 90
                img.save(filename=self.photo.path)
        if self.email:
            with Drawing() as draw:
                with Image(width=300,
                           height=30,
                           background=Color('white')) as emailimg:

                    draw.font = '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'
                    draw.font_color = 'black'
                    draw.font_size = 16
                    draw.text(5, int(emailimg.height * 12 / 13), self.email)

                    draw.draw(emailimg)
                    emailimg.save(filename=os.path.dirname(self.photo.path) +'/' + self.last_name + '.email.png')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Event(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField(help_text="Markdown syntax can be used!")
    created_date = models.DateTimeField(auto_now_add=True)
    edited_date = models.DateTimeField(auto_now=True)
    date = models.DateField()
    time = models.TimeField()
    publish = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)

    #objects = PostQuerySet.as_manager()

    def is_upcomming_event(self):
        return self.datetime >= timezone.now()

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        """Set slug"""
        if not self.slug:
            self.slug = slugify(self.title)
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Event post"
        verbose_name_plural = "Event posts"
        ordering = ["-created_date"]


class Project(models.Model):
    name = models.CharField(max_length=254, unique=True)
    stars = models.IntegerField(default=0)
    language = models.CharField(max_length=254, default='')
    github_id = models.IntegerField(blank=True, null=True)
    github_url = models.CharField(max_length=254, blank=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        """Set slug"""
        if not self.name:
            self.name = self.gh_name
        if not self.slug:
            self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    class Meta:
        ordering = ['slug']

    def __str__(self):
        return self.slug

kodkollektivet/forms.py
from django.forms import ModelForm

from .models import Project, Contributor


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('gh_name', 'gh_id', 'gh_url', 'gh_readme')


class ContributorForm(ModelForm):
    class Meta:
        model = Contributor
        fields = ('gh_login', 'gh_url', 'gh_id')

kodkollektivet/userprofile/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """A form that creates a user, with no priviledges.
    from email and password."""

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['first_name']

    class Meta:
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserCreationForm):
    """A form that changes a user, with no priviledges.
    from email and password."""

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['first_name']

    class Meta:
        model = CustomUser

kodkollektivet/views.py
from datetime import datetime, timedelta, time

from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView, ListView, DetailView
from django.utils import timezone
from django.views.generic.base import ContextMixin

from . import models


class FooterView(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(FooterView, self).get_context_data(**kwargs)
        context['upcoming_events'] = models.Event.objects.filter(
            date__gte=datetime.now())
        context['next_event'] = context['upcoming_events'].first
        context['old_events'] = models.Event.objects.all().order_by('date')
        return context


class IndexView(FooterView, TemplateView):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['header_text'] = 'Kodkollektivet'
        return context


class BoardTemplateView(FooterView, ListView):
    template_name = 'board.html'
    queryset = models.BoardMember.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BoardTemplateView, self).get_context_data(**kwargs)
        context['header_text'] = _('Board')
        return context


class ThanksTemplateView(FooterView, TemplateView):
    template_name = 'thanks.html'

    def get_context_data(self, **kwargs):
        context = super(ThanksTemplateView, self).get_context_data(**kwargs)
        context['header_text'] = _('Thanks')
        return context


class EventsListView(FooterView, ListView):
    queryset = models.Event.objects.all().order_by('-date')
    template_name = "events/events_list_view.html"

    def get_context_data(self, **kwargs):
        context = super(EventsListView, self).get_context_data(**kwargs)
        context['header_text'] = _('Events')
        return context


class EventsDetailView(FooterView, DetailView):
    model = models.Event
    template_name = "events/events_detail_view.html"


class ProjectsListView(FooterView, ListView):
    """Project List View"""
    model = models.Project
    template_name = 'projects/projects.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectsListView, self).get_context_data(**kwargs)
        context['header_text'] = _('Projects')
        return context

kodkollektivet/templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>Kodkollektivet</title>

    <meta property="og:title" content="➜ Kodkollektivet!" />
    <meta property="og:type" content="organization" />
    <meta property="og:url" content="http://kodkollektivet.se" />
    <meta property="og:image" content="{% static 'img/logo.png' %}" />

    <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">

    <script src="https://use.fontawesome.com/5c79208c6f.js"></script>

  </head>

  <body>
    <header>
      <div class="side">
	<a class="btn-open logo" href="{% url 'home' %}">
	  <img src="{% static 'img/logo_website.png' %}" />
	</a>

	<div class="social-icons">
	  <a href="https://www.facebook.com/kodkollektivet/" target="_blank">
	    <i class="fa fa-facebook-square" aria-hidde="true"></i>
	  </a>
	  <a href="https://github.com/Kodkollektivet" target="_blank">
	    <i class="fa fa-github" aria-hidde="true"></i>
	  </a>
	  <a href="https://twitter.com/kodkollektivet" target="_blank">
	    <i class="fa fa-twitter" aria-hidde="true"></i>
	  </a>
	</div>
      </div>

      {% include 'menu.html' %}

      <div class="header-text">
	<i class="fa fa-chevron-right" aria-hidde="true"></i>
	<h1>We are<br>Kodkollektivet</h1>
      </div>
    </header>

    <main>
      {% block content %}
      <div class="what-is">
	<img src="{% static '/img/kodkollektivet-ppl2.jpg' %}"/>
	<div class="split">
	  <i class="fa fa-chevron-right" aria-hidde="true"></i>
	</div>
	<article>
      	  <section>
            <h2>{% trans "What is Kodkollektivet" %}? </h2>
            <p>
              {% trans "what-is-kod-part-1" %}
	    </p>
	    <p>
              {% trans "what-is-kod-part-2" %}

              {% trans "what-is-kod-part-3" %}

              {% trans "what-is-kod-part-4" %}
            </p>
          </section>
	</article>
      </div>

      <div class="student-company">
	<article class="student">
      	  <section>
            <h2>{% trans "Student, do you have what it takes" %}?</h2>
            <p>
              {% trans "do-you-have-what-it-takes" %}
            </p>
          </section>
	</article>

	<div class="split">
	  <i class="fa fa-chevron-left" aria-hidde="true"></i>
	  <i class="fa fa-chevron-right" aria-hidde="true"></i>
	</div>
	<article class="company">
      	  <section>
            <h2>{% trans "Employers, come and meet the future" %}!</h2>
            <p>
              {% trans "come-and-meet-the-future" %}
            </p>
      	  </section>
	</article>
      </div>
      {% endblock %}
    </main>

    <footer>
      <div class="logo-footer">
        <a class="btn-open logo" href="{% url 'home' %}"><img src="{% static 'img/banner_stand.png' %}" /></a>
      </div>
      <div class="contact">
        <div>
          <h3>{% trans "Get in contact" %}</h3>
          <p>
            Email: info@kodkollektivet.se
          </p>
          <p>
            {% trans "We are using Slack" %},
            <a href="https://kodkollektivet.slack.com">
              https://kodkollektivet.slack.com
            </a>
          </p>
          <p>
            {% blocktrans %}
            As for now you need to send a mail to info@kodkollektivet.se and get an invite!
            Talk to you on Slack!
            {% endblocktrans %}
          </p>
        </div>
      </div>

      <div class="goto">
        <div>
          <div class="links">
            <ul class="pages">
              <h4>Pages</h4>
              <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
              <li><a href="{% url "kodkollektivet:eventslistview" %}">{% trans "Events" %}</a></li>
              <li><a href="{% url "kodkollektivet:boardtemplateview" %}">{% trans "Board" %}</a></li>
              <li><a href="{% url "kodkollektivet:projectslistview" %}">{% trans "Projects" %}</a></li>
            </ul>
            <ul class="sites">
              <h4>Sites</h4>
              <li><a href="https://github.com/Kodkollektivet" target="_blank">GitHub</a></li>
              <li><a href="https://www.facebook.com/kodkollektivet/" target="_blank">Facebook</a></li>
              <li><a href="https://github.com/Kodkollektivet/documents/blob/master/stadgar/stadgar.org" target="_blank">{% trans "Statutes" %}</a></li>
            </ul>
          </div>

          <div class="links">
            <ul class="event-links">
	      {% if upcomming_events %}
              <h4>Events</h4>
	      {% for event in upcomming_events|slice:":10" %}
              <li><a href="{% url "kodkollektivet:eventdetailview" event.slug %}">{{event}}</a></li>
	      {% endfor %}
	      {% else %}
	      <h4>Events</h4>
	      {% for event in old_events|slice:":10" %}
              <li><a href="{% url "kodkollektivet:eventdetailview" event.slug %}">{{event}}</a></li>
	      {% endfor %}
	      {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

kodkollektivet/templates/board.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}


<div class="board">
  {% for member in object_list %}
  <section>
    <div align="center">
      <h2>{{ member.position|title }}</h2>
      <img src={{ member.photo.url }} />
      <p>{{ member.first_name }} {{ member.last_name }}</p>
      {% if member.email %}<p>Email: <img src="/media/board-images/{{ member.last_name}}.email.png"/></p>{% endif %}
      {% if member.telephone %}<p>Tel:{{ member.telephone }}</p>{% endif %}
    </div>
  </section>
  {% endfor %}
</div>

{% endblock content %}

kodkollektivet/templates/menu.html
{% load i18n %}
<nav>
  <ul>
    <li><a href="{% url "kodkollektivet:eventslistview" %}">{% trans "Events" %}</a></li>
    <li><a href="{% url "kodkollektivet:projectslistview" %}">{% trans "Projects" %}</a></li>
    <li><a href="{% url "kodkollektivet:boardtemplateview" %}">{% trans "Board" %}</a></li>
  </ul>
</nav>

kodkollektivet/templates/thanks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

<section align="center">
  <h2>Special Thanks To</h2>
</section>
<hr/>

<section>
  <div align="center">
    <h1>Information Engineering Center (IEC)</h1>
    <p>IEC have been a huge help for Kodkollektivet since the beginning. They have been
      helping out not only with contacts and finance, but also with general guidance and
      structure in our growth as an organization.</p>
    <a href="http://iec2020.se/">iec2020.se</a></br>
    <img src="{% static 'img/companies/iec2016.png' %}"
         width="300" height="150" alt="IEC2020" />
  </div>
</section>
<hr>

{% endblock content %}