kodkollektivet/kodkollektivet_projects/urls.py
from django.conf.urls import url

from kodkollektivet_projects import github
from kodkollektivet_projects import views

urlpatterns = [
    url(r'^$', views.ProjectsListView.as_view(), name='projectslistview'),
    url(r'^contributor/(?P<slug>\S+)/$', views.ContributorDetailView.as_view(), name="contributordetailview"),
    url(r'^(?P<slug>\S+)/$', views.ProjectsDetailView.as_view(), name="projectdetailview"),
    url(r'^github/webhook$', github.GithubHook.as_view(), name='githubwebhook'),
]

kodkollektivet/urls.py
from django.conf.urls import url

from kodkollektivet import github
from kodkollektivet import views

urlpatterns = [
    url(r'^projects/$', views.ProjectsListView.as_view(), name='projectslistview'),
    url(r'^board/$', views.BoardTemplateView.as_view(), name='boardtemplateview'),
    url(r'^thanks/$', views.ThanksTemplateView.as_view(), name='thankstemplateview'),
    url(r'^events/$', views.EventsListView.as_view(), name="eventslistview"),
    url(r'^event/(?P<slug>\S+)/$', views.EventsDetailView.as_view(), name="eventdetailview"),
]

settings/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

from kodkollektivet import views

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.IndexView.as_view(), name='home'),
    re_path(r'^', include(('kodkollektivet.urls', 'kodkollektivet'), namespace='kodkollektivet')),
    # re_path(r'^i18n/', include('django.conf.urls.i18n')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kodkollektivet/models.py
# -*- coding: utf-8 -*-

from datetime import datetime, timedelta
import os

from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.conf import settings

from wand.image import Image
from wand.drawing import Drawing
from wand.color import Color

def handle_uploaded_file(fname, f):
    with open(fname, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)


class BoardMember(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, blank=True)
    telephone = models.CharField(max_length=50, blank=True)
    photo = models.ImageField(upload_to='board-images/')

    def save(self, *args, **kwargs):
        super(BoardMember, self).save(*args, **kwargs)
        if self.photo:
            with Image(filename=self.photo.path) as img:
                img.save(filename=self.photo.path+'.ORGINAL')
                img.transform(resize='x250')
                img.compression_quality = 90
                img.save(filename=self.photo.path)
        if self.email:
            with Drawing() as draw:
                with Image(width=300,
                           height=30,
                           background=Color('white')) as emailimg:

                    draw.font = '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'
                    draw.font_color = 'black'
                    draw.font_size = 16
                    draw.text(5, int(emailimg.height * 12 / 13), self.email)

                    draw.draw(emailimg)
                    emailimg.save(filename=os.path.dirname(self.photo.path) +'/' + self.last_name + '.email.png')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Event(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField(help_text="Markdown syntax can be used!")
    created_date = models.DateTimeField(auto_now_add=True)
    edited_date = models.DateTimeField(auto_now=True)
    date = models.DateField()
    time = models.TimeField()
    publish = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)

    #objects = PostQuerySet.as_manager()

    def is_upcomming_event(self):
        return self.datetime >= timezone.now()

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        """Set slug"""
        if not self.slug:
            self.slug = slugify(self.title)
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Event post"
        verbose_name_plural = "Event posts"
        ordering = ["-created_date"]


class Project(models.Model):
    name = models.CharField(max_length=254, unique=True)
    stars = models.IntegerField(default=0)
    language = models.CharField(max_length=254, default='')
    github_id = models.IntegerField(blank=True, null=True)
    github_url = models.CharField(max_length=254, blank=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        """Set slug"""
        if not self.name:
            self.name = self.gh_name
        if not self.slug:
            self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    class Meta:
        ordering = ['slug']

    def __str__(self):
        return self.slug

kodkollektivet/forms.py
from django.forms import ModelForm

from .models import Project, Contributor


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('gh_name', 'gh_id', 'gh_url', 'gh_readme')


class ContributorForm(ModelForm):
    class Meta:
        model = Contributor
        fields = ('gh_login', 'gh_url', 'gh_id')

kodkollektivet/userprofile/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """A form that creates a user, with no priviledges.
    from email and password."""

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['first_name']

    class Meta:
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserCreationForm):
    """A form that changes a user, with no priviledges.
    from email and password."""

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['first_name']

    class Meta:
        model = CustomUser

kodkollektivet/views.py
from datetime import datetime, timedelta, time

from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView, ListView, DetailView
from django.utils import timezone
from django.views.generic.base import ContextMixin

from . import models


class FooterView(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(FooterView, self).get_context_data(**kwargs)
        context['upcoming_events'] = models.Event.objects.filter(
            date__gte=datetime.now())
        context['next_event'] = context['upcoming_events'].first
        context['old_events'] = models.Event.objects.all().order_by('date')
        return context


class IndexView(FooterView, TemplateView):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['header_text'] = 'Kodkollektivet'
        return context


class BoardTemplateView(FooterView, ListView):
    template_name = 'board.html'
    queryset = models.BoardMember.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BoardTemplateView, self).get_context_data(**kwargs)
        context['header_text'] = _('Board')
        return context


class ThanksTemplateView(FooterView, TemplateView):
    template_name = 'thanks.html'

    def get_context_data(self, **kwargs):
        context = super(ThanksTemplateView, self).get_context_data(**kwargs)
        context['header_text'] = _('Thanks')
        return context


class EventsListView(FooterView, ListView):
    queryset = models.Event.objects.all().order_by('-date')
    template_name = "events/events_list_view.html"

    def get_context_data(self, **kwargs):
        context = super(EventsListView, self).get_context_data(**kwargs)
        context['header_text'] = _('Events')
        return context


class EventsDetailView(FooterView, DetailView):
    model = models.Event
    template_name = "events/events_detail_view.html"


class ProjectsListView(FooterView, ListView):
    """Project List View"""
    model = models.Project
    template_name = 'projects/projects.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectsListView, self).get_context_data(**kwargs)
        context['header_text'] = _('Projects')
        return context

kodkollektivet/templates/kodkollektivet_projects/contributor_detail_view.html
{% extends 'core/core.html' %}

{% block body %}
<div align="center">
  <p>{{ object.created | date:"d-m-Y" }}</p>
</div>
<div class="small-12 medium-8 medium-offset-1 columns" style="color: #93a1a1;">
  <img src="{{ object.gh_avatar }}"> <br>
  
  {{ object.name }}<br>

  {% if object.email %}
  {{ object.email }}<br>
  {% endif %}


  {% if object.gh_url %}
  {{ object.gh_url }}<br>
  {% endif %}

  {% if object.website %}
  {{ object.website }}<br>
  {% endif %}

  {% if object.linkedin %}
  {{ object.linkedin }}<br>
  {% endif %}
</div>

<div class="small-12 medium-3 columns" align="center">

  <div>
    {% if object.gh_url %}
    <h5>GitHub:</h5>
    <div>
      {% if object.gh_url %}
      <a href="{{ object.gh_url }}" target="_blank">{{ object.gh_url }}</a>
      {% endif %}
    </div>
    {% endif %}

  </div>


  <div class="small-12 medium-12 columns" align="center">
    {% if projects %}
    {% for p in projects %}
    <h3><a href="{% url "kodkollektivet:projectdetailview" p.slug %}">{{ p.name }}</a></h3>
    {% endfor %}
    {% else %}
    No projects
    {% endif %}
  </div>

</div>
{% endblock %}  

kodkollektivet/templates/kodkollektivet_projects/projects.html
{% extends 'core/core.html' %}

{% block body %}

  {% if object_list %}

    {% for project in object_list %}
      <section class="projectlist">
        <ul>
          <li><a href="{% url "kodkollektivet:projectdetailview" project.slug %}">{{ project.name }}</a></li>
        </ul>
      <section>      
    {% endfor %}

  {% else %}
    No projects
  {% endif %}

{% endblock %}

kodkollektivet/templates/kodkollektivet_projects/projects_detail_view.html
{% extends 'core/core.html' %}

{% block body %}
    <div align="center">
        <p>{{ object.created | date:"d-m-Y" }}</p>
    </div>
    <div class="small-12 medium-8 medium-offset-1 columns" style="color: #93a1a1;">
        {{ object.text | safe }}
    </div>

    <div class="small-12 columns" align="center">

        {% if object.gh_url %}
            <h5>GitHub:</h5>
            <div>
                {% if object.gh_url %}
                    <a href="{{ object.gh_url }}" target="_blank">{{ project.name }}</a>
                {% endif %}
            </div>
        {% endif %}

        <hr>

        <h5>Contributors:</h5>
        {% for c in contributors %}
        <h3><a href="{% url "kodkollektivet:contributordetailview" c.slug %}">{{ c.name }}</a></h3>
        {% endfor %}

        <hr>

        <h5>Languages:</h5>

        {% if languages %}
            {% for l in languages %}
                {{ l.name }}<br>
            {% endfor %}
        {% endif %}


        <hr>


        {% if frameworks %}
            <h5>Frameworks:</h5>

            {% for f in frameworks %}
                {{ f.name }}<br>
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}